### PR TITLE
add october psu blog post

### PR DESCRIPTION
**Pull request by gdams**

### CODE REVIEW

**Comment by gdams** [comment]
> Add change from Eclipse Foundation to Eclipse Adoptium for installers?

I don't think we made this change this time round?

**Review by jerboaa — APPROVED** [review]
Looks fine to me.

**Review by sxa — COMMENTED** [review]
I'd suggest adding something on the addition of source and static-libs files, since they are new if people want to have them. Doesn't have to be any more than this IMHO.
```
### New artifacts in the releases

While not yet available via the API, we now publish source and static versions of the temurin libraries (JDK11+) as well as source code archives in our github releases for anyone who wishes to make use of them.
```
Related: https://github.com/adoptium/adoptium.net/issues/213

**Comment by jerboaa** [comment]
> I'd suggest adding something on the addition of source and static-libs files, since they are new if people want to have them. Doesn't have to be any more than this IMHO.
> 
> ```
> ### New artifacts in the releases
> 
> While not yet available via the API, we now publish source and static versions of the temurin libraries (JDK11+) as well as source code archives in our github releases for anyone who wishes to make use of them.
> ```
> 
> Related: [adoptium/adoptium.net#213](https://github.com/adoptium/adoptium.net/issues/213)

They are available via the API:

```
$ curl -v https://api.adoptium.net/v3/binary/latest/17/ga/linux/x64/staticlibs/hotspot/normal/eclipse
*   Trying 20.62.244.126:443...
* Connected to api.adoptium.net (20.62.244.126) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=api.adoptium.net
*  start date: Aug 14 11:29:17 2021 GMT
*  expire date: Nov 12 11:29:15 2021 GMT
*  subjectAltName: host "api.adoptium.net" matched cert's "api.adoptium.net"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> GET /v3/binary/latest/17/ga/linux/x64/staticlibs/hotspot/normal/eclipse HTTP/1.1
> Host: api.adoptium.net
> User-Agent: curl/7.76.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 307 Temporary Redirect
< Date: Fri, 05 Nov 2021 11:35:27 GMT
< Content-Type: application/octet-stream
< Content-Length: 0
< Connection: keep-alive
< Location: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.1%2B12/OpenJDK17U-static-libs-glibc_x64_linux_hotspot_17.0.1_12.tar.gz
< 
* Connection #0 to host api.adoptium.net left intact
```

For sources see https://github.com/adoptium/adoptium.net/issues/213

**Comment by sxa** [comment]
> They are available via the API:

Thanks for confirming, in which case I recommend not including my proposed statement that they are not available there ;-)

**Review by sxa — APPROVED** [review]
Works for me if the sources are available on the web site (it's not immediately obvious how to get it if you're starting from https://adoptium.net/releases.html?variant=openjdk11 without going direct to the github release)

**Pull request merged**
